### PR TITLE
Created container for footer

### PR DESCRIPTION
**Pull request by arsalanhub**
Map of ABES Engineering College in home page.

### CODE REVIEW

**Comment by arsalanhub** [comment]
Also improved UI of Footer Section

**Comment by manav014** [comment]
Please update your branch with the master branch as the map is already updated

**Comment by arsalanhub** [comment]
Map is in contact form I have added it in index page and also made container for footer.

**Comment by manav014** [comment]
Thank you the footer section seems marvelous. May you please add this footer section to all the pages. Your PR would get high points for that.

**Comment by arsalanhub** [comment]
Sure.

**Pull request merged**
